// <auto-generated />
namespace Barometer.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class newmigration : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(newmigration));
        
        string IMigrationMetadata.Id
        {
            get { return "201401301536179_newmigration"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
